#!/bin/bash

# Auto-Build Environment Setup - Dashboard Session Persistence
# Generated by Planner Agent - Spec 001

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Dashboard Session Persistence"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check if services are already running
check_running() {
    local port=$1
    local name=$2
    if nc -z localhost $port 2>/dev/null; then
        echo -e "${YELLOW}$name already running on port $port${NC}"
        return 0
    fi
    return 1
}

# ============================================
# START SERVICES
# ============================================

PROJECT_ROOT="/Users/cory.naegle/Projects/swarm"

# Backend - Platform (Express on port 8080)
echo ""
echo "Starting Platform Backend..."
if check_running 8080 "Platform"; then
    echo "Using existing Platform instance"
else
    cd "$PROJECT_ROOT/apps/platform"
    npm run dev > "$PROJECT_ROOT/logs/platform.log" 2>&1 &
    PLATFORM_PID=$!
    echo "Platform PID: $PLATFORM_PID"
    wait_for_service 8080 "Platform" || exit 1
fi

# Frontend - Dashboard (Vite on port 3000)
echo ""
echo "Starting Dashboard Frontend..."
if check_running 3000 "Dashboard"; then
    echo "Using existing Dashboard instance"
else
    cd "$PROJECT_ROOT/apps/dashboard"
    npm run dev > "$PROJECT_ROOT/logs/dashboard.log" 2>&1 &
    DASHBOARD_PID=$!
    echo "Dashboard PID: $DASHBOARD_PID"
    wait_for_service 3000 "Dashboard" || exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Platform (Backend):  http://localhost:8080"
echo "  Dashboard (Frontend): http://localhost:3000"
echo ""
echo "API Endpoints:"
echo "  POST /api/auth/login   - User authentication"
echo "  GET  /api/auth/me      - Token validation"
echo "  POST /api/auth/logout  - Session termination"
echo "  POST /api/auth/refresh - Token refresh"
echo ""
echo "Logs:"
echo "  Platform: $PROJECT_ROOT/logs/platform.log"
echo "  Dashboard: $PROJECT_ROOT/logs/dashboard.log"
echo ""
echo "Next Steps:"
echo "  1. Navigate to http://localhost:3000/signin"
echo "  2. Login with valid credentials"
echo "  3. Verify token stored in localStorage"
echo "  4. Refresh page to test session persistence"
echo ""
echo "To stop services:"
echo "  pkill -f \"node.*platform\""
echo "  pkill -f \"node.*dashboard\""
echo ""
